### ISSUE TITLE
Error getting EC2 instance data when trying aws-importer.yml example

### ISSUE THREAD

**Issue by erikhromek** [Endava/endava-gsf-impactframework-plugins#1]
**Describe the bug**
It seems that plugin is not correctly getting EC2 instance data. You execute the plugin with the aws-importer.yml configured as input.

**To Reproduce**

1. Clone repository (using node 18 right now)
2. run npm install
3. configure aws-importer.yml, only difference is EC2 instance info:
```
      global-config:
        aws-importer:
          tag: green-software
          location: us-east-1
          aws-services: ec2
          aws-observation: 60
        metric:
          cloudwatch-namespace: 'CloudwatchAgentMetrics'
          client-namespace: 'AWS/EC2'
```

5. configure .env file with AWS credenciales
6. run ie --manifest ./examples/manifests/aws-importer.yml --output ./examples/manifests/aws-importer-computed.yml in root folder of project
7. execution outputs:

> error: 	The request must contain the parameter volumes
> MissingParameter: 	The request must contain the parameter volumes

**Expected behavior**
Plugin should run and complete the aws-importer-computed.yml with information and data from the instance.

**Screenshots**
![Captura desde 2024-04-16 18-57-46](https://github.com/Endava/endava-gsf-impactframework-plugins/assets/34162688/25099f86-35e0-4462-9474-8ca90e456e2b)

**Additional context**
We are just testing the plugin, don't know if it is 100% ready for end user usage. I don't know if this error is related to the plugin or related to AWS or Cloudwatch configuration.
